name: bld-ci

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build-bld-project:
    strategy:
      matrix:
        java-version: [ 17, 21, 25 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java-version }}

      - name: Cache bld dependencies
        id: cache-bld
        uses: actions/cache@v5
        with:
          path: lib
          key: ${{ runner.os }}-bld-${{ hashFiles('lib/bld/bld-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-bld-

      - name: Check for bld cache
        id: check-cache
        shell: bash
        run: |
          if [ -f "lib/bld/bld.cache" ]; then
            echo "cache_exists=true" >> $GITHUB_OUTPUT
          else
            echo "cache_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Download dependencies
        if: steps.check-cache.outputs.cache_exists == 'false'
        run: ./bld download

      - name: Update dependencies  
        if: steps.check-cache.outputs.cache_exists == 'true'
        run: ./bld updates

      - name: Compile source code
        run: ./bld compile